[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
(
    \.eggs
    | /{{cookiecutter.directory_name}}/tests
)
'''

[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
